// alertsData.js

export const alertsData = {
  couponOption: [32, 50, 100],
  users: [
    {
      id: 1,
      name: "Ama Serwaa",
      type: "premium",
      verified: true,
      level: "high",
      avatar: "https://randomuser.me/api/portraits/women/21.jpg",
      businessName: "Serwaa Studio",
      adsCount: 12,
    },
    {
      id: 2,
      name: "Kwame Ofori",
      type: "business",
      verified: true,
      level: "middle",
      avatar: "https://randomuser.me/api/portraits/men/45.jpg",
      businessName: "Ofori Enterprises",
      adsCount: 24,
    },
    {
      id: 3,
      name: "Linda Boateng",
      type: "basic",
      verified: false,
      level: "low",
      avatar: "https://randomuser.me/api/portraits/women/17.jpg",
      businessName: "Linda Boutique",
      adsCount: 2,
    },
    {
      id: 4,
      name: "Yaw Mensah",
      type: "premium",
      verified: false,
      level: "middle",
      avatar: "https://randomuser.me/api/portraits/men/31.jpg",
      businessName: "Mensah Tech",
      adsCount: 8,
    },
    {
      id: 5,
      name: "Akua Addo",
      type: "business",
      verified: true,
      level: "high",
      avatar: "https://randomuser.me/api/portraits/women/42.jpg",
      businessName: "Addo & Co",
      adsCount: 40,
    },
    {
      id: 6,
      name: "Kojo Asare",
      type: "basic",
      verified: false,
      level: "low",
      avatar: "https://randomuser.me/api/portraits/men/38.jpg",
      businessName: "Kojo's Repairs",
      adsCount: 1,
    },
    {
      id: 7,
      name: "Esi Owusu",
      type: "premium",
      verified: true,
      level: "high",
      avatar: "https://randomuser.me/api/portraits/women/28.jpg",
      businessName: "Owusu Media",
      adsCount: 15,
    },
    {
      id: 8,
      name: "Nana Kusi",
      type: "business",
      verified: false,
      level: "middle",
      avatar: "https://randomuser.me/api/portraits/men/27.jpg",
      businessName: "Kusi Traders",
      adsCount: 6,
    },
    {
      id: 9,
      name: "Efua Hammond",
      type: "basic",
      verified: false,
      level: "low",
      avatar: "https://randomuser.me/api/portraits/women/31.jpg",
      businessName: "Hammond Home",
      adsCount: 0,
    },
    {
      id: 10,
      name: "Kweku Appiah",
      type: "premium",
      verified: true,
      level: "middle",
      avatar: "https://randomuser.me/api/portraits/men/19.jpg",
      businessName: "Appiah Ventures",
      adsCount: 9,
    },
  ],

  admins: [
    {
      id: 1,
      name: "Jeff07",
      role: "Super Admin",
      avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    },
    {
      id: 2,
      name: "Adin",
      role: "Marketing Lead",
      avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    },
    {
      id: 3,
      name: "Oysloe",
      role: "Support Manager",
      avatar: "https://randomuser.me/api/portraits/men/44.jpg",
    },
    {
      id: 4,
      name: "Mina Dev",
      role: "Campaign Strategist",
      avatar: "https://randomuser.me/api/portraits/women/29.jpg",
    },
  ],

  ads: [
    {
      id: 1,
      title: "Toyota Hilux 2025 VX",
      price: 12600,
      durationDays: 6,
      category: "Automobile",
      image: "https://picsum.photos/id/1023/800/600",
    },
    {
      id: 2,
      title: "iPhone 16 Pro – Holiday Deal",
      price: 9200,
      durationDays: 4,
      category: "Electronics",
      image: "https://picsum.photos/id/1040/800/600",
    },
    {
      id: 3,
      title: "Weekend Getaway at Safari Lodge",
      price: 3500,
      durationDays: 3,
      category: "Travel",
      image:
        "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=800",
    },
    {
      id: 4,
      title: "50% Off Premium Membership",
      price: 0,
      durationDays: 7,
      category: "Subscription",
      image:
        "https://images.unsplash.com/photo-1590608897129-79da98d15969?w=800",
    },
    {
      id: 5,
      title: "Samsung QLED 70in TV",
      price: 11000,
      durationDays: 5,
      category: "Electronics",
      image: "https://picsum.photos/id/1010/800/600",
    },
    {
      id: 6,
      title: "Luxury Apartment – Cantonments",
      price: 45000,
      durationDays: 10,
      category: "Real Estate",
      image:
        "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800",
    },
  ],

  alerts: [
    {
      id: 1,
      message: "Enjoy 20% off your next ad boost!",
      type: "coupon",
      senderId: 1,
      code: "SAVE20",
      amount: 20,
      time: "2025-10-26T12:00:00Z",
      audience: 567,
      status: "active",
      relatedAds: [],
    },
    {
      id: 2,
      message: "We handpicked a few ads for you this festive break.",
      type: "adPromo",
      senderId: 2,
      time: "2025-10-25T12:00:00Z",
      audience: 230,
      status: "active",
      relatedAds: [1, 5],
    },
    {
      id: 3,
      message: "Upgrade to premium today and get one month free!",
      type: "coupon",
      senderId: 4,
      code: "UPGRADE1M",
      amount: 100,
      time: "2025-10-24T12:00:00Z",
      audience: 89,
      status: "active",
      relatedAds: [],
    },
    {
      id: 4,
      message: "Plan your weekend escape before slots run out.",
      type: "adPromo",
      senderId: 3,
      time: "2025-10-23T12:00:00Z",
      audience: 145,
      status: "expiring",
      relatedAds: [1, 2, 3, 4, 5, 6],
    },
    {
      id: 5,
      message: "View your latest engagement stats and insights.",
      type: "info",
      senderId: 1,
      time: "2025-10-21T12:00:00Z",
      audience: 64,
      status: "archived",
      relatedAds: [],
    },
  ],
};
