export const orderPageInfo = {
  subscription: [
    {
      name: "Basic  3x",
      tagLines: [
        "Share limited number of ads ",
        "All ads stays promoted for a week",
      ],
      discountedPrice: 567,
      actualPrice: 567,
    },
    {
      name: "Buisness  4x",
      tagLines: [
        "Pro partnership status ",
        "All ads stays promoted for a month",
      ],
      discountedPrice: 567,
      actualPrice: 567,
    },
    {
      name: "Platinum  10x",
      tagLines: [
        "Unlimited number of ads ",
        "Sell 10x faster in all categories",
      ],
      discountedPrice: 567,
      actualPrice: 567,
    },
  ],
  periods: ["all", "today", "week", "month", "yesterday"],
  dataCards: [
    {
      img: "https://randomuser.me/api/portraits/men/2.jpg",
      name: "Dr. Manhatten",
      buisnessName: "Brack Studios",
      subscription: "Platinum",
      timeAgo: 2,
      ads: { active: 900000, taken: 900, pending: 90 },
      buisnesses: { platinum: 90000, buisness: 90000, basic: 90000 },
    },
    {
      img: "https://randomuser.me/api/portraits/men/3.jpg",
      name: "Dr. Manhatten",
      buisnessName: "Brack Studios",
      subscription: "Platinum",
      timeAgo: 2,
      ads: { active: 900000, taken: 900, pending: 90 },
      buisnesses: { platinum: 90000, buisness: 90000, basic: 90000 },
    },
    {
      img: "https://randomuser.me/api/portraits/women/4.jpg",
      name: "Owusu Lisa",
      buisnessName: "Brack Studios",
      subscription: "Platinum",
      timeAgo: 2,
      ads: { active: 900000, taken: 900, pending: 90 },
      buisnesses: { platinum: 90000, buisness: 90000, basic: 90000 },
    },
    {
      img: "https://randomuser.me/api/portraits/men/6.jpg",
      name: "Dr. Manhatten",
      buisnessName: "Brack Studios",
      subscription: "Platinum",
      timeAgo: 2,
      ads: { active: 900000, taken: 900, pending: 90 },
      buisnesses: { platinum: 90000, buisness: 90000, basic: 90000 },
    },
    {
      img: "https://randomuser.me/api/portraits/women/1.jpg",
      name: "Dr. Manhatten",
      buisnessName: "Brack Studios",
      subscription: "Platinum",
      timeAgo: 2,
      ads: { active: 900000, taken: 900, pending: 90 },
      buisnesses: { platinum: 90000, buisness: 90000, basic: 90000 },
    },
    {
      img: "https://randomuser.me/api/portraits/women/2.jpg",
      name: "Kofi Kinatta",
      buisnessName: "Brack Studios",
      subscription: "Platinum",
      timeAgo: 2,
      ads: { active: 900000, taken: 900, pending: 90 },
      buisnesses: { platinum: 90000, buisness: 90000, basic: 90000 },
    },
  ],
  recentOrders: [
    { quantity: 10, name: "Daniel Shuko", timeAgo: "1 mins ago" },
    { quantity: 2, name: "Ama Shuko", timeAgo: "5 mins ago" },
    { quantity: 4, name: "Daniel Mensah", timeAgo: "10 min ago" },
    { quantity: 10, name: "Gorege King", timeAgo: "10 mins" },
    { quantity: 2, name: "John Shuko", timeAgo: "20 mins ago" },
    { quantity: 4, name: "Daniel Cave", timeAgo: "25 mins ago" },
  ],
};
