// src/api/supportData.js
export const supportData = {
  users: [
    {
      id: "u1",
      name: "Jessica Lincoln",
      role: "customer",
      verified: true,
      online: false,
      avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    },
    {
      id: "u2",
      name: "Sandra Bimpo",
      role: "customer",
      verified: false,
      online: true,
      avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    },
    {
      id: "u3",
      name: "Jeff07",
      role: "support",
      verified: true,
      online: true,
      avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    {
      id: "u4",
      name: "Jayson Laylo",
      role: "support",
      verified: true,
      online: false,
      avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    },
    {
      id: "u5",
      name: "Alberta Quayson",
      role: "customer",
      verified: false,
      online: true,
      avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    },
    {
      id: "u6",
      name: "Jaron",
      role: "customer",
      verified: false,
      online: false,
      avatar: "https://randomuser.me/api/portraits/men/20.jpg",
    },
    {
      id: "u7",
      name: "Jennifer Anderson",
      role: "customer",
      verified: true,
      online: false,
      avatar: "https://randomuser.me/api/portraits/women/21.jpg",
    },
    {
      id: "u8",
      name: "Arun Patel",
      role: "customer",
      verified: true,
      online: true,
      avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    },
    {
      id: "u9",
      name: "Maya Ross",
      role: "support",
      verified: true,
      online: true,
      avatar: "https://randomuser.me/api/portraits/women/25.jpg",
    },
    {
      id: "u10",
      name: "Carlos Vega",
      role: "customer",
      verified: false,
      online: false,
      avatar: "https://randomuser.me/api/portraits/men/44.jpg",
    },
    {
      id: "u11",
      name: "Lina Gomez",
      role: "customer",
      verified: true,
      online: true,
      avatar: "https://randomuser.me/api/portraits/women/47.jpg",
    },
    {
      id: "u12",
      name: "Olu A.",
      role: "support",
      verified: true,
      online: false,
      avatar: "https://randomuser.me/api/portraits/men/55.jpg",
    },
    {
      id: "u13",
      name: "Gordon Mensah",
      role: "customer",
      verified: true,
      online: true,
      avatar: "https://randomuser.me/api/portraits/men/69.jpg",
    },
  ],

  cases: [
    // Case 1 — short thread with image and read/unread
    {
      id: "case-1",
      userId: "u1",
      agents: ["u3"],
      status: "Closed",
      createdAt: "2025-10-19T10:00:00Z",
      updatedAt: "2025-10-20T15:00:00Z",
      messages: [
        {
          id: "case1-msg1",
          senderId: "u1",
          text: "Hi, can I grab your product? I need this item to buy.",
          timestamp: "2025-10-19T10:05:00Z",
          type: "text",
          readBy: ["u3"],
        },
        {
          id: "case1-msg2",
          senderId: "u3",
          text: "Sure! Which item are you referring to?",
          timestamp: "2025-10-19T10:06:00Z",
          type: "text",
          readBy: ["u1"],
        },
        {
          id: "case1-msg3",
          senderId: "u1",
          text: "",
          timestamp: "2025-10-19T10:07:00Z",
          type: "attachment",
          attachments: [
            {
              id: "case1-att1",
              type: "image",
              url: "https://images.pexels.com/photos/3739327/pexels-photo-3739327.jpeg",
            },
          ],
          readBy: [],
        },
      ],
    },

    // Case 2 — audio-heavy thread, unread for current agent(s)
    {
      id: "case-2",
      userId: "u2",
      agents: ["u3", "u4"],
      status: "Open",
      createdAt: "2025-10-20T08:30:00Z",
      updatedAt: "2025-10-21T12:00:00Z",
      messages: [
        {
          id: "case2-msg1",
          senderId: "u2",
          text: "Is the iPhone 15 Pro Max available today?",
          timestamp: "2025-10-20T08:30:00Z",
          type: "text",
          readBy: ["u4"],
        },
        {
          id: "case2-msg2",
          senderId: "u3",
          text: "Yes, it’s in stock. Would you like me to reserve one for you?",
          timestamp: "2025-10-20T08:32:00Z",
          type: "text",
          readBy: ["u2"],
        },
        {
          id: "case2-msg3",
          senderId: "u2",
          text: "",
          timestamp: "2025-10-20T08:33:00Z",
          type: "attachment",
          attachments: [
            {
              id: "case2-att1",
              type: "audio",
              url: "https://samplelib.com/lib/preview/mp3/sample-9s.mp3",
              duration: 9,
            },
          ],
          readBy: [],
        },
        {
          id: "case2-msg4",
          senderId: "u4",
          text: "I'm checking stock at two warehouses.",
          timestamp: "2025-10-20T09:01:00Z",
          type: "text",
          readBy: ["u2"],
        },
      ],
    },

    // Case 3 — long thread to test grouping + many messages
    {
      id: "case-3",
      userId: "u5",
      agents: ["u9"],
      status: "Open",
      createdAt: "2025-10-10T07:00:00Z",
      updatedAt: "2025-10-21T09:30:00Z",
      messages: [
        {
          id: "case3-msg1",
          senderId: "u5",
          text: "Hello — I received a damaged box.",
          timestamp: "2025-10-10T07:05:00Z",
          type: "text",
          readBy: ["u9"],
        },
        {
          id: "case3-msg2",
          senderId: "u9",
          text: "So sorry — can you share photos?",
          timestamp: "2025-10-10T07:07:00Z",
          type: "text",
          readBy: ["u5"],
        },
        {
          id: "case3-msg3",
          senderId: "u5",
          text: "",
          timestamp: "2025-10-10T07:08:00Z",
          type: "attachment",
          attachments: [
            {
              id: "case3-att1",
              type: "image",
              url: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg",
            },
          ],
          readBy: ["u9"],
        },
        {
          id: "case3-msg4",
          senderId: "u9",
          text: "Thanks — will process refund.",
          timestamp: "2025-10-11T12:00:00Z",
          type: "text",
          readBy: ["u5"],
        },
        {
          id: "case3-msg5",
          senderId: "u5",
          text: "Appreciate it.",
          timestamp: "2025-10-12T09:30:00Z",
          type: "text",
          readBy: ["u9"],
        },
        {
          id: "case3-msg6",
          senderId: "u9",
          text: "Refund complete — check your email.",
          timestamp: "2025-10-15T16:45:00Z",
          type: "text",
          readBy: ["u5"],
        },
        {
          id: "case3-msg7",
          senderId: "u5",
          text: "Got it — thanks!",
          timestamp: "2025-10-16T08:12:00Z",
          type: "text",
          readBy: ["u9"],
        },
      ],
    },

    // Case 4 — multiple agents, mixed attachments, recent timestamps
    {
      id: "case-4",
      userId: "u6",
      agents: ["u3", "u12"],
      status: "Open",
      createdAt: "2025-10-21T10:00:00Z",
      updatedAt: "2025-10-21T11:45:00Z",
      messages: [
        {
          id: "case4-msg1",
          senderId: "u6",
          text: "Hi, can I get discount?",
          timestamp: "2025-10-21T10:02:00Z",
          type: "text",
          readBy: [],
        },
        {
          id: "case4-msg2",
          senderId: "u3",
          text: "What's your order number?",
          timestamp: "2025-10-21T10:05:00Z",
          type: "text",
          readBy: ["u6"],
        },
        {
          id: "case4-msg3",
          senderId: "u6",
          text: "",
          timestamp: "2025-10-21T10:07:00Z",
          type: "attachment",
          attachments: [
            {
              id: "case4-att1",
              type: "image",
              url: "https://images.pexels.com/photos/3184396/pexels-photo-3184396.jpeg",
            },
          ],
          readBy: ["u3"],
        },
        {
          id: "case4-msg4",
          senderId: "u12",
          text: "I'll confirm with billing.",
          timestamp: "2025-10-21T11:30:00Z",
          type: "text",
          readBy: [],
        },
        {
          id: "case4-msg5",
          senderId: "u6",
          text: "Thanks — waiting.",
          timestamp: "2025-10-21T11:45:00Z",
          type: "text",
          readBy: [],
        },
      ],
    },

    // Case 5 — many short rapid messages (test autoscroll, grouping)
    {
      id: "case-5",
      userId: "u7",
      agents: ["u3"],
      status: "Open",
      createdAt: "2025-10-22T07:00:00Z",
      updatedAt: "2025-10-22T12:00:00Z",
      messages: [
        {
          id: "case5-msg1",
          senderId: "u7",
          text: "Morning",
          timestamp: "2025-10-22T07:01:00Z",
          type: "text",
          readBy: [],
        },
        {
          id: "case5-msg2",
          senderId: "u3",
          text: "Morning — how can I help?",
          timestamp: "2025-10-22T07:02:00Z",
          type: "text",
          readBy: ["u7"],
        },
        {
          id: "case5-msg3",
          senderId: "u7",
          text: "I need help with login",
          timestamp: "2025-10-22T07:03:00Z",
          type: "text",
          readBy: [],
        },
        {
          id: "case5-msg4",
          senderId: "u3",
          text: "Reset link sent.",
          timestamp: "2025-10-22T07:04:00Z",
          type: "text",
          readBy: ["u7"],
        },
        {
          id: "case5-msg5",
          senderId: "u7",
          text: "Working now, thanks.",
          timestamp: "2025-10-22T07:05:00Z",
          type: "text",
          readBy: ["u3"],
        },
      ],
    },

    // Case 6 — long attachments list
    {
      id: "case-6",
      userId: "u8",
      agents: ["u9"],
      status: "Open",
      createdAt: "2025-10-18T09:00:00Z",
      updatedAt: "2025-10-20T14:00:00Z",
      messages: [
        {
          id: "case6-msg1",
          senderId: "u8",
          text: "Sending product pictures.",
          timestamp: "2025-10-18T09:02:00Z",
          type: "text",
          readBy: ["u9"],
        },
        {
          id: "case6-msg2",
          senderId: "u8",
          text: "",
          timestamp: "2025-10-18T09:03:00Z",
          type: "attachment",
          attachments: [
            {
              id: "case6-att1",
              type: "image",
              url: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg",
            },
            {
              id: "case6-att2",
              type: "image",
              url: "https://images.pexels.com/photos/462235/pexels-photo-462235.jpeg",
            },
          ],
          readBy: ["u9"],
        },
        {
          id: "case6-msg3",
          senderId: "u9",
          text: "Looks good — scheduling pickup.",
          timestamp: "2025-10-19T08:30:00Z",
          type: "text",
          readBy: ["u8"],
        },
      ],
    },

    // Case 7 — edge case: conversation with only audio messages
    {
      id: "case-7",
      userId: "u10",
      agents: ["u12", "u3"],
      status: "Open",
      createdAt: "2025-10-14T13:00:00Z",
      updatedAt: "2025-10-14T13:20:00Z",
      messages: [
        {
          id: "case7-msg1",
          senderId: "u10",
          text: "",
          timestamp: "2025-10-14T13:02:00Z",
          type: "attachment",
          attachments: [
            {
              id: "case7-att1",
              type: "audio",
              url: "https://samplelib.com/lib/preview/mp3/sample-3s.mp3",
              duration: 3,
            },
          ],
          readBy: [],
        },
        {
          id: "case7-msg2",
          senderId: "u12",
          text: "Got your voice note — thanks.",
          timestamp: "2025-10-14T13:05:00Z",
          type: "text",
          readBy: ["u10"],
        },
        {
          id: "case7-msg3",
          senderId: "u10",
          text: "",
          timestamp: "2025-10-14T13:10:00Z",
          type: "attachment",
          attachments: [
            {
              id: "case7-att2",
              type: "audio",
              url: "https://file-examples.com/storage/fe1a7e1231b45802d3ce4f7/2017/11/file_example_MP3_700KB.mp3",
              duration: 7,
            },
          ],
          readBy: [],
        },
      ],
    },

    // Case 8 — old conversation to test date labels
    {
      id: "case-8",
      userId: "u11",
      agents: ["u9"],
      status: "Closed",
      createdAt: "2025-09-10T08:00:00Z",
      updatedAt: "2025-09-12T09:40:00Z",
      messages: [
        {
          id: "case8-msg1",
          senderId: "u11",
          text: "I have a billing question.",
          timestamp: "2025-09-10T08:05:00Z",
          type: "text",
          readBy: ["u9"],
        },
        {
          id: "case8-msg2",
          senderId: "u9",
          text: "Please DM invoice number.",
          timestamp: "2025-09-10T08:10:00Z",
          type: "text",
          readBy: ["u11"],
        },
        {
          id: "case8-msg3",
          senderId: "u11",
          text: "Sent.",
          timestamp: "2025-09-12T09:35:00Z",
          type: "text",
          readBy: ["u9"],
        },
      ],
    },

    // Case 9 — active large conversation with many back-and-forth messages
    {
      id: "case-9",
      userId: "u2",
      agents: ["u3"],
      status: "Open",
      createdAt: "2025-10-20T13:00:00Z",
      updatedAt: "2025-10-22T09:00:00Z",
      messages: [
        {
          id: "case9-msg1",
          senderId: "u2",
          text: "When will my order ship?",
          timestamp: "2025-10-20T13:01:00Z",
          type: "text",
          readBy: ["u3"],
        },
        {
          id: "case9-msg2",
          senderId: "u3",
          text: "Processing now — ETA 48 hours.",
          timestamp: "2025-10-20T13:10:00Z",
          type: "text",
          readBy: ["u2"],
        },
        {
          id: "case9-msg3",
          senderId: "u2",
          text: "Thanks.",
          timestamp: "2025-10-20T13:15:00Z",
          type: "text",
          readBy: ["u3"],
        },
        {
          id: "case9-msg4",
          senderId: "u2",
          text: "Also, can you gift wrap?",
          timestamp: "2025-10-21T09:00:00Z",
          type: "text",
          readBy: [],
        },
        {
          id: "case9-msg5",
          senderId: "u3",
          text: "Yes, add note to order.",
          timestamp: "2025-10-21T09:05:00Z",
          type: "text",
          readBy: [],
        },
        {
          id: "case9-msg6",
          senderId: "u2",
          text: "",
          timestamp: "2025-10-21T09:06:00Z",
          type: "attachment",
          attachments: [
            {
              id: "case9-att1",
              type: "image",
              url: "https://images.pexels.com/photos/414612/pexels-photo-414612.jpeg",
            },
          ],
          readBy: [],
        },
        {
          id: "case9-msg7",
          senderId: "u3",
          text: "Noted — will confirm when packed.",
          timestamp: "2025-10-22T08:45:00Z",
          type: "text",
          readBy: [],
        },
      ],
    },

    // Case 10 — spammy long thread (tests performance)
    {
      id: "case-10",
      userId: "u1",
      agents: ["u12"],
      status: "Open",
      createdAt: "2025-10-01T05:00:00Z",
      updatedAt: "2025-10-22T06:00:00Z",
      messages: Array.from({ length: 30 }).map((_, i) => ({
        id: `case10-msg-${i + 1}`,
        senderId: i % 3 === 0 ? "u1" : i % 3 === 1 ? "u12" : "u3",
        text: `Auto-generated message #${i + 1}`,
        timestamp: new Date(
          2025,
          9,
          1 + Math.floor(i / 3),
          6 + (i % 24),
          0,
          0
        ).toISOString(),
        type: "text",
        readBy: i % 3 === 0 ? ["u12"] : ["u1"],
      })),
    },

    // Case 11 — recent quick voice + image mix
    {
      id: "case-11",
      userId: "u8",
      agents: ["u9"],
      status: "Open",
      createdAt: "2025-10-22T09:10:00Z",
      updatedAt: "2025-10-22T09:30:00Z",
      messages: [
        {
          id: "case11-msg1",
          senderId: "u8",
          text: "Quick voice note",
          timestamp: "2025-10-22T09:11:00Z",
          type: "text",
          readBy: [],
        },
        {
          id: "case11-msg2",
          senderId: "u8",
          text: "",
          timestamp: "2025-10-22T09:12:00Z",
          type: "attachment",
          attachments: [
            {
              id: "case11-att1",
              type: "audio",
              url: "https://samplelib.com/lib/preview/mp3/sample-6s.mp3",
              duration: 6,
            },
          ],
          readBy: [],
        },
        {
          id: "case11-msg3",
          senderId: "u9",
          text: "Received — thanks.",
          timestamp: "2025-10-22T09:25:00Z",
          type: "text",
          readBy: ["u8"],
        },
      ],
    },

    // Case 12 — cross-day messages for label testing
    {
      id: "case-12",
      userId: "u5",
      agents: ["u3"],
      status: "Open",
      createdAt: "2025-10-19T23:00:00Z",
      updatedAt: "2025-10-22T01:00:00Z",
      messages: [
        {
          id: "case12-msg1",
          senderId: "u5",
          text: "Late night question",
          timestamp: "2025-10-19T23:12:00Z",
          type: "text",
          readBy: [],
        },
        {
          id: "case12-msg2",
          senderId: "u3",
          text: "Replying in the morning",
          timestamp: "2025-10-20T08:30:00Z",
          type: "text",
          readBy: ["u5"],
        },
        {
          id: "case12-msg3",
          senderId: "u5",
          text: "Thanks!",
          timestamp: "2025-10-21T00:45:00Z",
          type: "text",
          readBy: ["u3"],
        },
        {
          id: "case12-msg4",
          senderId: "u5",
          text: "",
          timestamp: "2025-10-22T00:02:00Z",
          type: "attachment",
          attachments: [
            {
              id: "case12-att1",
              type: "image",
              url: "https://images.pexels.com/photos/210661/pexels-photo-210661.jpeg",
            },
          ],
          readBy: [],
        },
      ],
    },
  ],
};
